CREATE  DATABASE test;
 
use test;
 
 
CREATE TABLE DEPT (
DEPTNO              int NOT NULL,
DNAME               VARCHAR(14),
LOC                 VARCHAR(13),
CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));
INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');
CREATE TABLE EMP (
EMPNO               int NOT NULL,
ENAME               VARCHAR(10),
JOB                 VARCHAR(9),
MGR                 int CONSTRAINT EMP_SELF_KEY REFERENCES EMP (EMPNO),
HIREDATE            DATE,
SAL                 decimal,
COMM                decimal,
DEPTNO              int NOT NULL,
CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (EMPNO));
INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-81',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-81',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-81',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-81',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-81',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-81',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-82',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-83',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);
 
SELECT *
FROM EMP
WHERE JOB IN ('CLERK', 'MANAGER')
 
 
SELECT GETDATE();
 
 
SELECT * 
FROM EMP
WHERE SAL BETWEEN 500 AND 1000
 
 
SELECT *
FROM EMP
WHERE MONTH(HIREDATE) = '12';
 
SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 2500
 
SELECT *
FROM EMP
WHERE SAL IN (800,950,3000,5000);
 
SELECT *
FROM EMP
WHERE ENAME LIKE '_l%';
 
 
SELECT *
FROM EMP
WHERE ENAME LIKE '%D';
 
SELECT *
FROM EMP 
WHERE LEN(ENAME) = 5;
 
SELECT *
FROM EMP
WHERE ENAME LIKE 'T%R'
 
SELECT *
FROM EMP
WHERE ENAME LIKE '%A%'
 
SELECT *
FROM EMP
WHERE DAY(HIREDATE ) < 19;
 
SELECT EMPNO
FROM EMP
WHERE ENAME = 'JAMES'
 
SELECT SAL
FROM EMP
WHERE ENAME = 'KING';
 
SELECT *
FROM EMP
WHERE JOB = 'PRESIDENT';
 
SELECT *
FROM EMP
WHERE JOB = 'MANAGER';
 
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;
 
------------------------ SECOND LIST
 
SELECT DNAME, COUNT(ENAME)
FROM DEPT
FULL OUTER JOIN EMP
ON DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME
HAVING COUNT(ENAME) = 0
 

SELECT *
FROM EMP
WHERE MGR IS NULL
 
SELECT COUNT(ENAME) AS PEOPLE
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC = 'CHICAGO';
 
SELECT ENAME
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC = 'CHICAGO';

 
SELECT ENAME, DEPT.LOC
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
ORDER BY DEPT.LOC
 
SELECT DNAME, COUNT(ENAME)
FROM DEPT
FULL OUTER JOIN EMP
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME
 
 
SELECT COUNT(DISTINCT(MGR))
FROM EMP
 
SELECT *
FROM EMP
WHERE MGR IS NULL
 
SELECT ENAME, DEPTNO
FROM EMP
WHERE ENAME = 'SMITH';
 
SELECT ENAME, JOB, DEPT.LOC
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'SALESMAN' AND DEPT.LOC = 'BOSTON';
 
SELECT ENAME, DEPT.LOC
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
 
 
SELECT * 
FROM EMP
WHERE SAL <
(
SELECT SAL
FROM EMP
WHERE ENAME = 'MILLER'
)
 
 
SELECT *
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DEPT.LOC = 'CHICAGO'
 
SELECT ENAME, SAL
FROM EMP
WHERE SAL >
(SELECT MIN(SAL)
FROM EMP
WHERE JOB = 'MANAGER')
 
SELECT ENAME,EMPNO
FROM EMP
WHERE DEPTNO =
(
SELECT DEPTNO
FROM DEPT
WHERE DNAME = 'ACCOUNTING'
)
 
SELECT *
FROM EMP E1
INNER JOIN EMP E2
ON E1.HIREDATE> E2.HIREDATE AND E1.MGR = E2.EMPNO;
 

SELECT *,
	CASE
		WHEN DEPT.DNAME != 'SALES' THEN 'NON SALES'
		WHEN SAL > 1000 THEN CONVERT(VARCHAR, SAL)
		ELSE '1000'
	END AS TEXT 
FROM EMP
FULL OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO


SELECT DNAME
FROM DEPT D
WHERE NOT EXISTS (SELECT 1 FROM EMP E WHERE E.DEPTNO = D.DEPTNO)
 
 
 
SELECT *
FROM EMP
ORDER BY JOB